
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04


suites:
  - name: standalone_node
    run_list:
      - recipe[locustio::default]
    attributes:
      locustio:
        base_url: chef.io
        uri_list:
          - {'uri': '/chef/', 'weight': '20', 'identifier': 'what_is_chef'}
          - {'uri': '/resources', 'weight': '20', 'identifier': 'chef_resources'}
          - {'uri': '/getting-started', 'weight': '20', 'identifier': 'getting_started'}
          - {'uri': '/resources/solutions', 'weight': '20', 'identifier': 'resource_solutions'}
          - {'uri': '/solutions/aix', 'weight': '20', 'identifier': 'solutions_aix'}
        node_type: 'standalone'
        custom_test_file: 'custom_test.py'

  - name: master_node
    run_list:
      - recipe[locustio::default]
    attributes:
      locustio:
        base_url: chef.io
        uri_list:
          - {'uri': '/chef/', 'weight': '20', 'identifier': 'what_is_chef'}
          - {'uri': '/resources', 'weight': '20', 'identifier': 'chef_resources'}
          - {'uri': '/getting-started', 'weight': '20', 'identifier': 'getting_started'}
          - {'uri': '/resources/solutions', 'weight': '20', 'identifier': 'resource_solutions'}
          - {'uri': '/solutions/aix', 'weight': '20', 'identifier': 'solutions_aix'}
        node_type: 'master'
        custom_test_file: 'custom_test.py'



